### ISSUE TITLE
typo in 'getting texts'

### ISSUE THREAD

**Issue by fenimore** [sgsinclair/alta#1]
There are two typos in the  alta/ipynb/GettingTexts.ipynb file: 
after prompt 28, your wrote "withouth" 

the more significant typo is after prompt 37, you write that totalCharacters += chars is equivalent to totalCharacters += chars -- I think you mean totalCharacters += chars is equivalent to totalCharacters = totalCharacters + chars

**Comment by sgsinclair** [comment]
Thanks!

669def1795e31247b9fc1fc6691cef3c70cb05b0
