### ISSUE TITLE
regex 

### ISSUE THREAD

**Issue by rschafish** [sgsinclair/alta#7]
Have been reviewing the code to be sure I understand what is going on and could not find an explanation for  a portion of the line   listOfTokens = re.findall(r'\b\w[\w-]*\b', fileRead.lower())

Cannot find definition of the term [\w-] in python documentation  for regex etc.    Explanation would be appreciated.

Cheers, BobS

**Comment by GeoffreyRockwell** [comment]
Dear Bob,

This line of code we have found tokenizes texts faster than, for example, the NLTK approach. The python documentation doesn’t really go into detail on regular expressions, you probably need a good book on that. 

My understanding of how this works is the following:

\w = an alphanumeric character

[\w-] = an alphanumeric character or hyphen (this is to catch hyphenated words)

[\w-]* = 0 to any number of such chapters

\w[\w-]* = an alphanumeric character followed by zero to any number of characters or hyphens (this avoids treating as words things that start with hyphens)

\b … \b = surrounded by a word boundary

Stéfan may correct me,

Geoffrey Rockwell

**Comment by rschafish** [comment]
Hi Geoffrey

 

Thanks for the feedback…  that is very helpful…as I noted in my comment I simply could not find an example/explanation of the \w- term.    What I want to do is modify the code to extract the paragraph around the word of interest.  While it will generate more text, I find that a complete paragraph can be more informative than a sentence or +_ xxx words.

 

Cheers, BobS

**Comment by sgsinclair** [comment]
Geoffrey explained it as well as I could. What might be a bit confusing is that "-" is meant as the hyphen character, not as a quantifier like "+".

In your case it might be easier (though slower – but so what?) to go through each paragraph one at a time to see if there's a match.
